name: Add issues to Jozu planning project

on:
  issues:    
    types: 
        - opened
       
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3   ## v3.1.1
        with:
          app-id: ${{ vars.KITOPS_BOT_ID }}
          private-key: ${{ secrets.KITOPS_BOT_PRIVATE_KEY }}
          owner: kitops-ml

      - name: Add To GitHub projects
        uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd  ## v2.0.0
        with:
          project-url: https://github.com/orgs/jozu-ai/projects/1
          github-token: ${{ steps.generate-token.outputs.token }}
